
			// This class was auto-generated by AnimationCooker
			using System.Collections.Generic;
			using AnimCooker;
			public static class AnimDb
			{
				public static void Populate(DoubleDictionary<string, AnimDbEntry> dict)
				{
				dict["FirstRobot", "Rest"] = new AnimDbEntry { BeginFrame = 0, EndFrame = 20, Interval = 0.07692308f, ModelName = "FirstRobot", ClipName = "Rest", ModelIndex = 5, ClipIndex = 0 };
				dict["FirstRobot", "Movement"] = new AnimDbEntry { BeginFrame = 21, EndFrame = 41, Interval = 0.07692308f, ModelName = "FirstRobot", ClipName = "Movement", ModelIndex = 5, ClipIndex = 1 };
				dict["FirstRobot", "Attack"] = new AnimDbEntry { BeginFrame = 42, EndFrame = 59, Interval = 0.07692308f, ModelName = "FirstRobot", ClipName = "Attack", ModelIndex = 5, ClipIndex = 2 };
				dict["FirstRobot", "Recharge"] = new AnimDbEntry { BeginFrame = 60, EndFrame = 80, Interval = 0.07692308f, ModelName = "FirstRobot", ClipName = "Recharge", ModelIndex = 5, ClipIndex = 3 };
				dict["FirstRobot", "Death_1"] = new AnimDbEntry { BeginFrame = 81, EndFrame = 101, Interval = 0.07692308f, ModelName = "FirstRobot", ClipName = "Death_1", ModelIndex = 5, ClipIndex = 4 };
				dict["FirstRobot", "Death_2"] = new AnimDbEntry { BeginFrame = 102, EndFrame = 115, Interval = 0.07692308f, ModelName = "FirstRobot", ClipName = "Death_2", ModelIndex = 5, ClipIndex = 5 };
				}
			public enum Model { FirstRobot }
			public enum FirstRobot { Rest, Movement, Attack, Recharge, Death_1, Death_2}
			}