
			// This class was auto-generated by AnimationCooker
			using System.Collections.Generic;
			using AnimCooker;
			public static class AnimDb
			{
				public static void Populate(DoubleDictionary<string, AnimDbEntry> dict)
				{
				dict["just_robot", "Armature|Atack"] = new AnimDbEntry { BeginFrame = 0, EndFrame = 7, Interval = 0.1666667f, ModelName = "just_robot", ClipName = "Armature|Atack", ModelIndex = 4, ClipIndex = 0 };
				dict["just_robot", "Armature|Death_1"] = new AnimDbEntry { BeginFrame = 8, EndFrame = 17, Interval = 0.1666667f, ModelName = "just_robot", ClipName = "Armature|Death_1", ModelIndex = 4, ClipIndex = 1 };
				dict["just_robot", "Armature|Death_2"] = new AnimDbEntry { BeginFrame = 18, EndFrame = 24, Interval = 0.1666667f, ModelName = "just_robot", ClipName = "Armature|Death_2", ModelIndex = 4, ClipIndex = 2 };
				dict["just_robot", "Armature|Movement"] = new AnimDbEntry { BeginFrame = 25, EndFrame = 34, Interval = 0.1666667f, ModelName = "just_robot", ClipName = "Armature|Movement", ModelIndex = 4, ClipIndex = 3 };
				dict["just_robot", "Armature|Recharge"] = new AnimDbEntry { BeginFrame = 35, EndFrame = 44, Interval = 0.1666667f, ModelName = "just_robot", ClipName = "Armature|Recharge", ModelIndex = 4, ClipIndex = 4 };
				dict["just_robot", "Armature|Rest"] = new AnimDbEntry { BeginFrame = 45, EndFrame = 54, Interval = 0.1666667f, ModelName = "just_robot", ClipName = "Armature|Rest", ModelIndex = 4, ClipIndex = 5 };
				}
				public enum Model { LardAssSpider, Horse, robot_mite, Just_warrior_test, just_robot }
				public enum LardAssSpider { Attack, Death, Idle, Run, Walk}
			public enum Horse { Horse_Walk, Horse_Idle, Horse_Run}
			public enum robot_mite { Armaturego, Armaturefire}
			public enum Just_warrior_test { Rest, Recharge, Movement, Death, Attack}
			public enum just_robot { ArmatureAtack, ArmatureDeath_1, ArmatureDeath_2, ArmatureMovement, ArmatureRecharge, ArmatureRest}
			}